apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimus-travel-backend
  labels:
    app: optimus-travel-backend
    env: dev
spec:
  selector:
    matchLabels:
      app: optimus-travel-backend
  template:
    metadata:
      labels:
        app: optimus-travel-backend
    spec:
      containers:
      - name: backend
        image: nijusupai/optimus-travel:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1