kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: optimus-travel-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimus-travel-frontend
  labels:
    app: optimus-travel-frontend
    env: dev
spec:
  selector:
    matchLabels:
      app: optimus-travel-frontend
  template:
    metadata:
      labels:
        app: optimus-travel-frontend
    spec:
      containers:
      - name: frontend
        # env:
        # - name: REACT_APP_APIHOSTPORT
        #   value: http://52.226.198.63:3000
        image: nijusupai/optimus-travel-front-end:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1